###
GET http://127.0.0.1:8005/alma

###
GET http://127.0.0.1:8005/alma/usuarios

###
POST http://127.0.0.1:8005/alma/usuarios
Content-Type: application/json

{
  "nombre":"Julia paramo",
  "correo": "julia@paramo.com"
}

###
PUT http://127.0.0.1:8005/alma/usuarios/12

###
DELETE http://127.0.0.1:8005/alma/usuarios/123