###
GET http://127.0.0.1:8005/alma/usuarios

###
POST http://127.0.0.1:8005/alma/usuarios
Content-Type: application/json

{
  "nombre":"luz conde",
  "correo":"luz@conde.com"
}

###
PUT http://127.0.0.1:8005/alma/usuarios/12

###
DELETE http://127.0.0.1:8005/alma/usuarios/123